# Generated by Django 3.0.5 on 2020-05-14 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=10)),
                ('strength', models.IntegerField()),
                ('cls_teacher', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('present_strngth', models.IntegerField()),
                ('sub', models.CharField(max_length=10)),
                ('teacher_name', models.CharField(max_length=30)),
                ('classes', models.CharField(max_length=20)),
                ('school_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
